// Generated by LiveScript 1.2.0
(function(){
  var gulp, del, gulpUtil, gulpLivescript, gulpStylus, gulpJade, gulpWebpack, gulpWatch, gulpLivereload;
  gulp = require('gulp');
  del = require('del');
  gulpUtil = require('gulp-util');
  gulpLivescript = require('gulp-livescript');
  gulpStylus = require('gulp-stylus');
  gulpJade = require('gulp-jade');
  gulpWebpack = require('gulp-webpack');
  gulpWatch = require('gulp-watch');
  gulpLivereload = require('gulp-livereload');
  gulp.task('build:server', function(){
    return gulp.src('./server/*.ls').pipe(gulpLivescript({
      bare: true
    })).on('error', function(it){
      throw it;
    }).pipe(gulp.dest('./build'));
  });
  gulp.task('build:client', function(){
    return gulp.src('./client/*.ls').pipe(gulpLivescript({
      bare: true
    })).on('error', function(it){
      throw it;
    }).pipe(gulp.dest('./build/client'));
  });
  gulp.task('build', ['build:server', 'build:client']);
  gulp.task('pack', ['build:client'], function(){
    return gulp.src('./build/client/*.js').pipe(gulpWebpack()).pipe(gulp.dest('./public'));
  });
  gulp.task('clean', function(cb){
    return del(['./build/**'], cb);
  });
  gulp.task('default', ['build', 'pack']);
}).call(this);
