// Generated by LiveScript 1.3.0
(function(){
  var gulp, del, gulpNodemon, gulpUtil, gulpLivescript, gulpStylus, nib, fluidity, gulpJade, gulpWebpack, gulpWatch, gulpLivereload, isProduction, defaultTasks;
  gulp = require('gulp');
  del = require('del');
  gulpNodemon = require('gulp-nodemon');
  gulpUtil = require('gulp-util');
  gulpLivescript = require('gulp-livescript');
  gulpStylus = require('gulp-stylus');
  nib = require('nib');
  fluidity = require('fluidity');
  gulpJade = require('gulp-jade');
  gulpWebpack = require('gulp-webpack');
  gulpWatch = require('gulp-watch');
  gulpLivereload = require('gulp-livereload');
  isProduction = process.env.NODE_ENV === 'production';
  gulp.task('build:stylus', function(){
    return gulp.src('./client/stylus/master.styl').pipe(gulpStylus({
      use: [nib(), fluidity()],
      compress: true
    })).pipe(gulp.dest('./public'));
  });
  gulp.task('build:server', function(){
    return gulp.src('./server/*.ls').pipe(gulpLivescript({
      bare: true
    })).on('error', function(it){
      throw it;
    }).pipe(gulp.dest('./build'));
  });
  gulp.task('build:client', function(){
    return gulp.src('./client/*.ls').pipe(gulpLivescript({
      bare: true
    })).on('error', function(it){
      throw it;
    }).pipe(gulp.dest('./build/client'));
  });
  gulp.task('build', ['build:server', 'build:client', 'build:stylus']);
  gulp.task('pack', ['build:client'], function(){
    return gulp.src('./build/client/*.js').pipe(gulpWebpack()).pipe(gulp.dest('./public'));
  });
  gulp.task('watch', function(){
    livereload.listen();
    return gulp.watch('build/**');
  });
  gulp.task('clean', function(cb){
    return del(['./build/**'], cb);
  });
  gulp.task('develop', ['build'], function(){
    return gulpNodemon({
      script: './build/main.js'
    });
  });
  defaultTasks = ['build', 'pack'];
  if (!isProduction) {
    defaultTasks.push('develop');
  }
  gulp.task('default', defaultTasks);
}).call(this);
